
name: Deploy app DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
    
      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/app/_meta
      
      - name: Build image
        run: docker build -t registry.digitalocean.com/test-cont/digital-ocean-deploy:$(echo $GITHUB_SHA | head -c7) .
      
      - name: Instal doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ dop_v1_0ae7e75c797b4268935df7707395115ac44daf5b864d820e62ec28e5057cc9c7 }}

      - name: Login docker
        run: doctl registry login --expiry-seconds 600

      - name: Push image
        run: docker push registry.digitalocean.com/test-cont/digital-ocean-deploy:$(echo $GITHUB_SHA | head -c7) 

      